name: Feature Request
description: Ask for specific feature to be added
title: "[Feature Request]: <feature_name>"
labels: ["feature-request"]

body:
    - type: textarea
      id: request
      attributes:
          label: Request
          description: Please list the feature or improvement you would like.
          placeholder: A command that will ...
      validations:
          required: true

    - type: textarea
      id: ideas
      attributes:
          label: Solution ideas
          description: A clear description of how you would like this implemented.
          placeholder: The command should respond with exactly...

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context here.
          placeholder: I consider this command necessary because ...

    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md).
          options:
              - label: I agree to follow this project's **Code of Conduct**
                required: true
